2242 - Added OWASP Maven Dependency checker
amido/stacks-java pull request #65
Opened 2020-08-05 15:44 UTC by Akrish17

[2242 - Added OWASP Maven Dependency checker]

#### 📲 What

Added OWASP Maven Dependency checker in the pom.xml

#### 🤔 Why

To detect publicly disclosed vulnerabilities contained within a project’s maven dependencies.

#### 🛠 How

OWASP will determine if there is a Common Platform Enumeration (CPE) identifier for a given dependency. If found, it will generate a report linking to the associated CVE entries.
Need to run `mvn clean install -Powasp-dependency-check` as part of each build. This will generate a dependency-check-report.html under the target folder. 

#### 👀 Evidence
![image](https://user-images.githubusercontent.com/67281032/89433862-bc924900-d73a-11ea-8484-42bf077591b4.png)

#### 🕵️ How to test

Notes for QA

#### ✅ Acceptance criteria Checklist

- [ ] Code peer reviewed?
- [ ] Documentation has been updated to reflect the changes?
- [ ] Passing all automated tests, including a successful deployment?
- [ ] Passing any exploratory testing?
- [ ] Rebased/merged with latest changes from development and re-tested?
- [ ] Meeting the Coding Standards?

2020-08-05 16:07 UTC, ElvenSpellmaker commented
Does this need anything to hook into the build?

2020-08-05 16:14 UTC, Akrish17 commented
> Does this need anything to hook into the build?

Yes

2020-08-05 17:02 UTC, ekartsonakisamido commented on java/pom.xml
> +                        <version>5.3.2</version>
Use the `property` defined above.

2020-08-05 17:02 UTC, ekartsonakisamido commented on java/pom.xml
> +        <dependency-check-maven.version>5.3.2</dependency-check-maven.version>
Let's use the naming convention, ie `owasp-dependency-check-plugin.version` .

2020-08-05 17:03 UTC, ekartsonakisamido requested changes
Minor comments left inline.

2020-08-05 17:05 UTC, ekartsonakisamido commented
> > Does this need anything to hook into the build?
> 
> Yes

@ElvenSpellmaker update the build command:
`mvn clean install [...] -Powasp-dependency-check` and
publish the generated reports - @Akrish17 what's the directory & name of the report please ?

2020-08-05 17:08 UTC, ElvenSpellmaker commented
@ekartsonakisamido We can't publish the reports as a nice HTML page due to how AZD works, but we can for now attach them as a build artefact for people to download and look at.

> mvn clean install [...] -Powasp-dependency-check
About the command to use to run it, do you know which plug-in and goal it's run under please? We're trying to separate steps out so running whole lifecycles kinda ruins the flow in Azure DevOps.

2020-08-05 17:10 UTC, ElvenSpellmaker commented
The `Test` tab and `Code Coverage` tabs are special tabs, and you can't define your own tabs without extensions.

2020-08-05 17:14 UTC, ekartsonakisamido commented
> @ekartsonakisamido We can't publish the reports as a nice HTML page due to how AZD works, but we can for now attach them as a build artefact for people to download and look at.
> 
> > mvn clean install [...] -Powasp-dependency-check
> 
> About the command to use to run it, do you know which plug-in and goal it's run under please? We're trying to separate steps out so running whole lifecycles/phases kinda ruins the flow in Azure DevOps.

I'd like to understand the limitation of AZD, it's trivial to publish reports in other CI tools. 

The plugin is `dependency-check:check` and runs on the maven `verify` stage.

2020-08-05 17:17 UTC, ElvenSpellmaker commented
Sure, let's have a chat about it. 🙂 

Also, as a slight aside the Code Coverage report is also parsed and any external CSS/JS is stripped, leading me to have to use a `node` container in the build to run some tasks for inlining the resources:
https://github.com/amido/stacks-java/blob/master/build/azDevops/azure/templates/steps/build-java.yml#L102-L111

using the files here: 
https://github.com/amido/stacks-java/tree/master/build/azDevops/azure/coverage

2020-08-06 08:24 UTC, Akrish17 commented
> > > Does this need anything to hook into the build?
> > 
> > 
> > Yes
> 
> @ElvenSpellmaker update the build command:
> `mvn clean install [...] -Powasp-dependency-check` and
> publish the generated reports - @Akrish17 what's the directory & name of the report please ?

@ekartsonakisamido  the reports are generated in the Target folder and the file generated is called dependency-check-report.html. All these information is added to the task i have created for @ElvenSpellmaker

2020-08-06 08:25 UTC, ekartsonakisamido commented
> > > > Does this need anything to hook into the build?
> > > 
> > > 
> > > Yes
> > 
> > 
> > @ElvenSpellmaker update the build command:
> > `mvn clean install [...] -Powasp-dependency-check` and
> > publish the generated reports - @Akrish17 what's the directory & name of the report please ?
> 
> @ekartsonakisamido the reports are generated in the Target folder and the file generated is called dependency-check-report.html. All these information is added to the task i have created for @ElvenSpellmaker

brilliant

2020-08-06 08:26 UTC, ekartsonakisamido approved these changes

2020-08-06 08:28 UTC, Akrish17 commented
> @ekartsonakisamido We can't publish the reports as a nice HTML page due to how AZD works, but we can for now attach them as a build artefact for people to download and look at.
> 
> > mvn clean install [...] -Powasp-dependency-check
> 
> About the command to use to run it, do you know which plug-in and goal it's run under please? We're trying to separate steps out so running whole lifecycles/phases kinda ruins the flow in Azure DevOps.

so this check is added in maven pom.xml as a profile 
![image](https://user-images.githubusercontent.com/67281032/89509340-1b050900-d7c7-11ea-8202-a0ed32b52d68.png)
This is the command that needs to be used to generate the report -- mvn clean install -Powasp-dependency-check

2020-08-06 08:53 UTC, merged